### ISSUE TITLE
RFC: multiple tokens and different token generators

### ISSUE THREAD

**Issue by bravo-kernel** [UseMuffin/Tokenize#6]
It took some figuring out but I finally discovered the beauty of this plugin. However, there are 3 things I would like to add/change before I could actually use this, I hope we can discuss.

### Intro: how does it work

I will come up with a PR for the readme so new users can more easily understand the logic behind using the plugin. 

Summarized the token record stores all new fields values for a foreign record and automatically updates that foreign record with the new values once the token verifies, quite brilliant ☺️ 

1. generate a token
2. specify related table to be updated (`foreign_table`)
3. specify which record (`foreign_key`) in the related table needs to be updated if token verification succeeds
4. specify the new field values (`foreign_data`) you want updated in the record if token verification succeeds

### RFC1. Token generating

I would like to implement more flexible token generating, preferably using a lib already dedicated to that purpose. I am using https://github.com/ircmaxell/RandomLib myself and think it would be nice if we could support its "Generators". This way we can generate all sorts of tokens (chars, numbers, etc) from weak to strong. 

### RFC2. Token verification

Currently, the `verify` function simply looks if a token record exists with given `token` value and `status` 0.

IMO this makes sense in the current implementation but dropping the `UNIQUE` limitation on the database (if we would implement token generating as described above which could lead to e.g. duplicate short sized PINs per user) would IMO require another check on the find. Having looked at other solutions it could be something like the `user_id`.

### RFC3: Multiple tokens/types

Currently, it does not seem possible to generate multiple tokens (even though updating mullitple fields using a single token works). Let's take the following example assuming RFC1 is implemented:

- token with value `123456` generated for password reset, updates `password` field in `Users` table with `foreign_id` 1
- token with value `aab98b213586277493941eb740331ef9` generated for confirming `email` field in the same `Users` table with same foreign key.

Again, looking at other solutions this could be solved by adding an (optional) `token_type` field where we can store stuff like `default`, `password-reset`, `email-verification`. This way the unique idenitifier could be userid/token-value/token-type. Adding this to the custom find would round up things.

### Closing note

I realize this proposal introduces a big change to the original idea but feel it could be a good one as it would make it generic enough to apply to all use-cases.  **Feedback appreciated.**

**Comment by phillaf** [comment]
Switchable token library is a good idea. 

I'm a little more on the fence about RFC2. Enforcing token uniqueness from within the plugin is a cool thing to have, but imposes some kind of limitations. Dropping all limitations would be cool but prevents us from enforcing uniqueness from within the plugin.

As for rfc3, I think the rationale is that you can't process a password recovery via email unless you accept the email as verified first. Therefore not needing dual fields. It never occurred to me before, but you're right that if multiple recovery method are supported, then this assumption becomes false. +1 for that.

**Comment by bravo-kernel** [comment]
Maybe my example for 3 wasn't too smart so maybe this helps, taking the token lifetime into the equation:

- user registers with username and email
- email-validation token is generated with 1 month lifetime
- app uses the username, does not enfore email validation for friendly/easy onboarding
- user forgets his password after two weeks

**Comment by bravo-kernel** [comment]
Goodmorning mr. @Phillaf, as far as RFC2 goes:

- the plugin now enforces uniqueness on the `token` field and this is indeed a good thing
- I am suggesting that we keep enforcing uniqueness from within the plugin but use a two column composite constraint instead (e.g. `token` and `user_id`)

This way we can prevent clashes when using simple tokens like **123456** in combination with many users.

I have also given thought about using even more fields (like `foreign_table` and `foreign_id`) for the constraint to make things fail-proof but that would probably be overkill for what's to be achieved, 

What do you think?

**Comment by ADmad** [comment]
- RFC1:  I don't want to add any hard external dependency. Currently tokens are generated using `openssl_random_pseudo_bytes()` or `random_bytes()` which are good enough for majority of uses cases. So if you want to implement an adapter interface with defaults being the same then it's fine by me.

- RFC2: I don't think uniqueness along with another field is necessary. Just use universally unique tokens. If someone wants to use "dumb" tokens like `123456` they can roll the own stuff :)

- RFC3: Allow multiple tokens per `foreign_table` & `foreign_key` pair could be useful. So :+1:  for that.
  Config could be like

```php
'fields' => [
    '<token_type>' => ['field1', 'field2'],
    '<token_type>' => ['field3']
]
```

**Comment by bravo-kernel** [comment]
As for the 'dumb' tokens... they seem to be used mostly for SMS messages. Got them today on my phone in 6 and 8 digit format from bank, Microsoft and work remote login.

**Comment by bravo-kernel** [comment]
Would it be an idea to solve the `uniqueness` discussion by:

- sticking to unique tokens (and thus keeping the single-column constraint as it is now)
- simply generating another token in case a duplicate key is generated (and the save fails)

It looks like combining this approach with the `token_type` field would solve most if not all problems.

**Comment by ADmad** [comment]
Sounds good.

**Comment by bravo-kernel** [comment]
Thanks for the patience, I believe we are currently at this point:

1. introduce a new column named `token_type`
2. implement an adapter interface for the token generating logic (current method as default)
3. do **not** change the current `UNIQUE` constraint, tokens will stay unique within the plugin

Which would lead to something like this:

![image](https://cloud.githubusercontent.com/assets/230500/22403043/034daf70-e60c-11e6-8c1c-587c86c1f7a7.png)

Two questions remain:

- do we agree that we need to implement a configurable `verify()` where we not only look for the `token` value but also for `foreign_table` and `foreign_key` (to prevent false positive in situations where a token value exists but the record does not match e.g. logged in user-id)?
- do we accept that functional duplicates can exist in the plugin (like the password-reset example in red above)? If not, four-column uniqueness is back on the table again.

FWIW I am being a bit thorough (bitchy) here but this would be a core part of my commercial app, implicitly meaning I will have to commit to help maintaining it 😉

**Comment by ADmad** [comment]
>  do we agree that we need to implement a configurable verify() where we not only look for the token value but also for foreign_table and foreign_key (to prevent false positive in situations where a token value exists but the record does not match e.g. logged in user-id)?

If tokens are unique I don't see the need to checking any additional fields. With token based auth in general isn't it the user's responsibility to ensure no one else has access to his tokens?

> do we accept that functional duplicates can exist in the plugin (like the password-reset example in red above)? If not, four-column uniqueness is back on the table again.

If tokens are unique duplicates in other columns are no problem.

**Comment by bravo-kernel** [comment]
I (finally) get your point mr. @ADmad. It seems most functionality I'm chasing after should reside in the application logic and not this plugin.  In that light, I now also think I don't need the automated logic of the behavior. As brilliant as it is I will have to build logic around the various `token_types` anyway and updating the related entity is only a small extra step then.

Closing as my PR would destroy the simplicity/beauty of this plugin. Also apologies for the long strain but this was hard to get my head around. Again much appreciated, I will take the input for my plugin-attempt 👍
