### ISSUE TITLE
Add a token_type field for use in token verification of tokens with different purposes.

### ISSUE THREAD

**Issue by SAThomsen** [UseMuffin/Tokenize#9]
In the case of validating tokens with specific purposes, say password reset tokens vs. refer a friend tokens, it would be useful to have a token_type to distinguish the two. Does it make sense to extend the functionality of this plugin, or would it make more sense to build a standalone plugin that depends on the functionality provided from this?

**Comment by ADmad** [comment]
Sounds reasonable, though all relevant methods for getting and setting tokens will have to be updated to account for token type. If you would like to make a PR go for it.

**Comment by SAThomsen** [comment]
Cool, I'll look into extending the plugin then :)

**Comment by ADmad** [comment]
Closing as the issue has gone stable.
